spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:devinecodemy}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          gitlab:
            authorization-grant-type: authorization_code
            redirect−uri: ${CODELAND_BACKEND_BASE_URL:{baseUrl}}/login/oauth2/code/{registrationId}
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid , read_user , profile
            provider: gitlab
            client-authentication-method: basic
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/oauth/userinfo
            jwk-set-uri: https://gitlab.com/oauth/discovery/keys
            user-name-attribute: sub
  web:
    resources:
      static-locations:
        classpath: '/resources/static/'
logging:
  level:
    org:
      springframework:
        security: DEBUG

codeland:
  frontend:
    url: ${CODELAND_FRONTEND_BASE_URL:http://localhost:3000}

